# Generated by Django 3.2.2 on 2021-05-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
    ]
