# Generated by Django 3.2.2 on 2021-05-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_val',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
